apiVersion: v1
kind: Service
metadata:
  name: AKS_Demo
  namespace: namespace-workflow-1710126585783
spec:
  type: LoadBalancer
  selector:
    app: AKS_Demo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000